### ISSUE TITLE
[Task] Display the values from the sensor in the speedometer

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-Cluster#10]
### Description

Display the speed from the sensor #8 in the lcd created in #9

### Priority

Low

### Story Reference

- #11

**Comment by luis-ffe** [comment]
# Finished ✅
- [x] LCD working.
- [x] CanBus communication is working with the Rasp .

## Next steps
- Get the cross compilation working for Raspberry Pi OS.
- Installing Qt on the Rasp is something we are avoiding due its size.
- Further development would be having no OS on the rasp only the app, research needed.
