### ISSUE TITLE
Development Pipeline CD/CI - Define full pipeline for cluster

### ISSUE THREAD

**Issue by luis-ffe** [SEAME-pt/Team02-Cluster#14]
# Description

- Create a full Implementation of a working pipeline using all the tools.
- Research.
- Keep ADR
- Documentation of everything all decisions
- Markdown diagrams easy to change
- Follow Misra Guidelines / codeQl
- Automated tests with gherkin framework and other scrips
- Version Control
- Set the Scrum sprint organization a keep the cicle going

**Comment by Rui-Pedro-Pires** [comment]
3 Different workflows created, one for the clang-format, it will automaticle format the code following some rules of misra, another workflow added was the clang-tidy that will compile the code and check for errors in the compilation, and finaly the deploy workflow to compile the code on push to main, and to test it in a selfhosted machine and when compiled it will send the executables to the car specific directory, allowing them to be used in the services that are automatically initialized.
