### ISSUE TITLE
[Story] Get acquainted with CAN Bus, sensoring, Qt

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-Cluster#4]
### Description

The CAN communication module is responsible for communicating with the speed sensor via the CAN bus. It receives speed data from the speed sensor and passes it on to the main application for display. This module uses the CAN library provided by Qt to communicate with the speed sensor.

### Epic Reference

- #3 

### Priority

Medium

**Comment by luis-ffe** [comment]
# ✅ DONE  ✅ 

- [x] All the task for this have been completed 
- [x] CAN BUS protocol research
- [x] Communication established between a sender and receiver Arduino with CAN BUS shield and the same with MCP2515
- [x] Communication sender/receiver in both micro-controllers established successfully
- [x] set up that turns lamp on receiving CAN signal
- [x] set up that reads sensor input from received by the CAN BUS
- [ ] Use of QT library for the communication 👎 

### 🔒 CLOSED 🔒
