### ISSUE TITLE
[Task] Receive values from the speed sensor

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-Cluster#8]
### Description

Receive values from the speed sensor in the arduion and use can bus protocol to send it to the jetson nano board

### Priority

Medium

### Story Reference

#11

**Comment by luis-ffe** [comment]
# Finished ✅
- [x] CanBus communication is working both for the car peripherals and the Rasp attached to LCD (tested).

## Next steps
- Full integration of the APP( Rasp OS/LCD)  with Jetson and peripherals in a contiguous way.
