### ISSUE TITLE
[Task] Display a speedometer in a lcd

### ISSUE THREAD

**Issue by Rui-Pedro-Pires** [SEAME-pt/Team02-Cluster#9]
### Description

Create a speedometer component to display the information of the speed sensor in a lcd

### Priority

Medium

### Story Reference

- #11

**Comment by luis-ffe** [comment]
# Finished ✅
- [x] Qt QML project set up and working according to what was defined.
- [x] Relevant information like the battery and speed gauge implemented.
- [ ] Cross compilation problems have slowed the deployment of the front-end app to the Raspberry Pi OS further research and implementation needed in the next sprint to have the app running on boot on the rasp OS.
- [x] CanBus communication is working both for the car peripherals and the Rasp attached to LCD.

## Next steps
- Get the cross compilation working for Raspberry Pi OS.
- Installing Qt on the Rasp is something we are avoiding due its size.
- Further development would be having no OS on the rasp only the app, research needed.
